title: Aiman Anizan
author: AimanAnizan56
email: anizanaimann1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site is for practise purpose. There is nothing yet to see. Once
  I get to used with github, I will create a new fresh website about
  myself for study, work and sharing knowledge purpose.

# social links
twitter_username: aimanemay # DO NOT include the @ character, or else the build will fail!
github_username:  AimanAnizan56 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
